### ISSUE TITLE
QGroundControl doesn't receive data from an UDP Port 

### ISSUE THREAD

**Issue by martinareds** [mavlink/qgc-user-guide#354]
Hi everyone, I'm new to QGroundControl. 
I wrote a Python script where I take my GPS data from a USB port. Then, I create an UDP Client to send the obtained data to the QGC. Unfortunately, these data aren't read by the QGroundControl (which I have read that behaves like an UDP Server). These are my code and the settings I put on QGC:
```
master = mavutil.mavlink_connection('udpin:0.0.0.0:14550') 
...
gps = serial.Serial("/dev/ttyUSB1", 4800)
...
while(open):
try:
	resp = gps.readline() 
except serial.SerialException as e:
	print('QGround is trying to access at the same USB1 port') 
client_sock.sendto(resp, ('127.0.0.1', 27000))
```
![WhatsApp Image 2022-08-08 at 16 22 08 (1)](https://user-images.githubusercontent.com/49305647/183444238-82b67d3c-888b-4c09-915e-951f2fbab5e0.jpeg)
![WhatsApp Image 2022-08-08 at 16 22 08](https://user-images.githubusercontent.com/49305647/183444245-a5e83234-b01a-4ab0-9dd8-4339ffef8cd0.jpeg)
What am I doing wrong? I also created another python script to emulate a UDP Server and it gets the data correctly.

**Comment by hamishwillee** [comment]
Hi @martinareds This repo is for creating issues about the docs, not technical support - best place to raise this is https://discuss.px4.io/c/qgroundcontrol/15

Thing to remember though is that QGC is a ground control station. It expects to see an autopilot and may well not connect if the thing it connects to does not identify as such. Normally QGC listens on port 14550 for heartbeats and then connects. I THINK it can also connect to the remote port (i.e. initiate rather than listen for a connection) - try port 18570

Other than that, your best bet is the discussion boards. If no response in a day or two then cross link the discussion to slack.
